# Generated by Django 4.2.3 on 2023-07-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dsite',
            table='advertisements',
        ),
    ]
